travis:
  secure:
    BINSTAR_TOKEN: iKWtkOXOCyHya1cJ84FWgt51ndzQIQvcIMjzL3TSJesWQOl3vMma3lOGUE2XCuG3n+IxA+4K+YNGTJMxWHo4++rnaJ6ZkOK2zlEa6LOx3VHsKdh1T07zvu/J+g+hQp7a8a3HYdFiaNk3SOauuydjC4fZUpa90mJxmlwrNpHqHOY13i1Vn52jQ/Pvq0jCb33htd6j3nctXpMrTaNYm36tu5hPnr0USxd+A1NwSu3Zu4BAChLG0cGL0NiYH1hUf0Eh6fze/KBtJKabziu1dpiKfXW8oYB/vnkMh5hJU3ID0XiU3BRnNqzQnkpkPwfVJnFDoQWRCOpwS7BcPXRGNjVh1pZmzzJ/jRtUqIbko567JY4h/MGDow5IQNqjEgCtxyXA+lu0TdbeD0B/Jqbt3u0VIdkUttt6LgqKLplIHznX8iO03hCRkK6Bqwey4KeafEWxymutNiyzMDLHlfeG2waelxPJ0CKp2D1uEQm8c/k5LxpIv2oaOE5y+KtponPIs0shlUHkvRxDgRVdXBxh6FkehoGPamqLK1SEUFXbUQjv0ohWNRix8yIT/oZ7EuDnAf0RAWnB/PeyjBS50wnS1Siaz1vSvhgRzK0wzfsFxf0QArDzKaipEuJwedTQwvjELTui1qciNC+xzesTwSpTteKyk2TAZPBTJxsQOWyWHLOnFcw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
