travis:
  secure:
    BINSTAR_TOKEN: SzT2W1UJFs+hEHeYq4/njDZdXGNSRC/HtHic8mmgebFfqjWN8qKWnfUTIs4obC3j+1OU7mV5rvxWCaLA2FQXyERhpPhWPA3GAcfjaFoIYZxFvb65esvtEr41Z3oVSVB6J/e258lZhbvhgP7p6n734Cw2x/sf8liY+F8+s2iAk+Gd4zG7jWoxU7a4lixkwn1uXjPFZcNwPaQbK+AO277ZV8ziPWonyl2iar7o6DXW8jZsMn/mq4prNZE3WEiPsbrTPixRL3BzLzikSNZAPt9uLmPyEZ3WsrWmYHB54V9N5Iqfz4cH4xafYC/5+WtjVHxbE3CQiKCcq0ZgTKUoXL6a1jSNCNKJag2RW0py1vpUMakWmCzmVV8pzxTNYN5DYx7EGEee6mbllpn6MxD2MHZ17ETz28bcfbyCVz9qO9P3cCHHg5BYl4J7/HwPr+uqPFNxPUqo8xuT5GIY3cXaQRInVNQRXJdFR4Yiaml7EsT1Kqsce4emtriU9qhikO3uMsBzw7XMRIlja4ULnTzok8942iQpXU6pvN1huiom5Ks++9hVSDZtaWfBYmDfSOHxBd40JrNUngpc4gtvuyoO3fmaN3Si0c9gb5woYRB45VB+zYp15iTE/OlqfcnR7ZoC3vmfyTt0kMplGylugAP+qNscUtuLzs2CMDPxBf4fEJEI9eU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
